version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      # Install Sphinx and documentation dependencies
      - pip install sphinx>=8.1.3 sphinx-autodoc-typehints>=3.0.1 sphinx-rtd-theme>=3.0.2 myst-parser>=4.0.0
      # Install the SDK package from the sdk directory
      - pip install -e ./sdk

sphinx:
  configuration: docs/sphinx/source/conf.py
