version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install uv package manager
      - pip install uv
    post_install:
      # Install the SDK package and its dependencies from the sdk directory
      # First, install the package itself
      - cd sdk && uv pip install --system -e .
      # Then install the dev dependencies which include Sphinx and related tools
      - uv pip install --system sphinx>=8.1.3 sphinx-autodoc-typehints>=3.0.1 sphinx-rtd-theme>=3.0.2 myst-parser>=4.0.0

sphinx:
  configuration: docs/sdk/source/conf.py

