backends:
  deepeval:
    module: "rhesis.sdk.metrics.providers.deepeval"
    factory: "DeepEvalMetricFactory"
  ragas:
    module: "rhesis.sdk.metrics.ragas"
    factory: "RagasMetricFactory"
  rhesis:
    module: "rhesis.sdk.metrics.rhesis"
    factory: "RhesisMetricFactory"
  custom:
    module: "rhesis.sdk.metrics.rhesis"
    factory: "RhesisMetricFactory"
