{{- if .Values.database.enabled }}
{{- if eq .Values.database.type "postgresql" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    tier: database
    {{- include "rhesis.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      tier: database
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.database.postgresql.image.repository }}:{{ .Values.database.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.database.postgresql.image.pullPolicy | default .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.secrets.configMaps.existingConfigMap }}
                  key: SQLALCHEMY_DB_NAME
            - name: POSTGRES_USER
              value: {{ .Values.database.postgresql.auth.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.postgresql.auth.existingSecret }}
                  key: {{ .Values.database.postgresql.auth.secretKeys.password }}
          resources:
            {{- toYaml .Values.database.postgresql.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-init-script
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.database.postgresql.auth.username }}
                - -d
                - {{ .Values.database.postgresql.auth.database }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.database.postgresql.auth.username }}
                - -d
                - {{ .Values.database.postgresql.auth.database }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-init-script
          configMap:
            name: postgres-init-config
{{- end }}
{{- end }}
