{{- if .Values.database.enabled }}
{{- if eq .Values.database.type "postgresql" }}
{{- if .Values.database.postgresql.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    tier: database
    {{- include "rhesis.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.postgresql.persistence.size }}
  {{- if .Values.database.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.database.postgresql.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
