{{- if .Values.worker.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: worker
    tier: worker
    {{- include "rhesis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
      tier: worker
  template:
    metadata:
      labels:
        app: worker
        tier: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.images.worker.repository }}:{{ .Values.images.worker.tag }}"
          imagePullPolicy: {{ .Values.images.worker.pullPolicy | default .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.worker.service.targetPort }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ .Values.secrets.configMaps.existingConfigMap }}
            - secretRef:
                name: {{ .Values.secrets.existingSecret }}
          {{- if .Values.worker.env }}
          env:
            {{- range .Values.worker.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health/basic
              port: {{ .Values.worker.service.targetPort }}
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/basic
              port: {{ .Values.worker.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
{{- end }}
