templates:
  - id: gdpr-compliance
    name: GDPR Compliance
    description: Test privacy and data protection compliance
    color: primary.main
    icon: ShieldIcon
    behaviors:
      - Compliance
      - Privacy
      - Transparency
      - Accountability
      - Data Minimization
      - Security
    topics:
      - GDPR
      - Data Protection
      - User Rights
      - Consent Management
      - Data Portability
      - Privacy by Design
    category:
      - Legal
      - Privacy
      - Regulatory
      - Data Governance
      - Compliance Auditing
      - Risk Management
    scenarios:
      - Data Access Request
      - Right to be Forgotten
      - Consent Withdrawal
      - Data Breach Notification
      - Cross-Border Transfer
      - Privacy Impact Assessment
    popularity: high

  - id: bias-detection
    name: Bias Detection
    description: Identify and test for AI biases
    color: secondary.main
    icon: BalanceIcon
    behaviors:
      - Fairness
      - Reliability
      - Objectivity
      - Inclusivity
      - Equity
      - Consistency
    topics:
      - Bias
      - Fairness
      - Demographics
      - Representation
      - Discrimination
      - Algorithmic Justice
    category:
      - Ethics
      - Quality
      - AI Safety
      - Social Impact
      - Diversity
      - Responsible AI
    scenarios:
      - Gender Bias
      - Racial Bias
      - Age Bias
      - Socioeconomic Bias
      - Cultural Bias
      - Disability Bias
    popularity: high

  - id: performance-testing
    name: Performance Testing
    description: Test response quality and latency
    color: warning.main
    icon: SpeedIcon
    behaviors:
      - Reliability
      - Performance
      - Scalability
      - Efficiency
      - Responsiveness
      - Stability
    topics:
      - Speed
      - Quality
      - Consistency
      - Latency
      - Throughput
      - Resource Usage
    category:
      - Performance
      - Quality
      - System Testing
      - Optimization
      - Load Testing
      - Stress Testing
    scenarios:
      - High Load
      - Edge Cases
      - Error Handling
      - Concurrent Users
      - Peak Traffic
      - Resource Constraints
    popularity: high

  - id: hallucination-detection
    name: Hallucination Detection
    description: Detect factual inaccuracies
    color: error.main
    icon: PsychologyIcon
    behaviors:
      - Reliability
      - Accuracy
      - Truthfulness
      - Verifiability
      - Consistency
      - Groundedness
    topics:
      - Facts
      - Accuracy
      - Verification
      - Citations
      - Evidence
      - Source Attribution
    category:
      - Quality
      - Reliability
      - Trust
      - Information Integrity
      - AI Safety
      - Content Validation
    scenarios:
      - Fact Checking
      - Source Verification
      - Citation Accuracy
      - Contradictory Claims
      - Made-up References
      - False Confidence
    popularity: medium

  - id: medical-safety
    name: Medical Safety
    description: Test healthcare AI applications
    color: success.main
    icon: HealthAndSafetyIcon
    behaviors:
      - Safety
      - Compliance
      - Accuracy
      - Reliability
      - Confidentiality
      - Clinical Validity
    topics:
      - Medical
      - Safety
      - HIPAA
      - Clinical Guidelines
      - Patient Care
      - Healthcare Standards
    category:
      - Healthcare
      - Safety
      - Regulatory
      - Medical Ethics
      - Patient Protection
      - Clinical Risk
    scenarios:
      - Medical Advice
      - Patient Privacy
      - Diagnosis Recommendations
      - Medication Information
      - Emergency Situations
      - Informed Consent
    popularity: medium

  - id: financial-compliance
    name: Financial Compliance
    description: Test financial service regulations
    color: info.main
    icon: AccountBalanceIcon
    behaviors:
      - Compliance
      - Security
      - Transparency
      - Accountability
      - Risk Management
      - Due Diligence
    topics:
      - Financial
      - Regulations
      - Security
      - Anti-Money Laundering
      - Know Your Customer
      - Fraud Prevention
    category:
      - Finance
      - Legal
      - Regulatory
      - Banking
      - Financial Services
      - Risk Assessment
    scenarios:
      - KYC
      - AML
      - Transaction Security
      - Suspicious Activity
      - Customer Verification
      - Regulatory Reporting
    popularity: medium

  - id: security-testing
    name: Security Testing
    description: Test for security vulnerabilities
    color: error.dark
    icon: SecurityIcon
    behaviors:
      - Security
      - Reliability
      - Robustness
      - Resilience
      - Protection
      - Defense
    topics:
      - Security
      - Vulnerabilities
      - Attacks
      - Threat Detection
      - Data Protection
      - System Hardening
    category:
      - Security
      - Testing
      - Cybersecurity
      - Penetration Testing
      - Risk Mitigation
      - Threat Analysis
    scenarios:
      - Prompt Injection
      - Data Leakage
      - Adversarial Attacks
      - Jailbreak Attempts
      - Sensitive Information Exposure
      - Authorization Bypass
    popularity: high

  - id: accessibility
    name: Accessibility
    description: Test for accessibility compliance
    color: warning.dark
    icon: AccessibilityNewIcon
    behaviors:
      - Accessibility
      - Compliance
      - Inclusivity
      - Usability
      - Universal Design
      - Equitable Access
    topics:
      - Accessibility
      - WCAG
      - Inclusivity
      - Assistive Technology
      - Disability Support
      - ADA Compliance
    category:
      - Accessibility
      - Legal
      - Usability
      - Inclusive Design
      - User Experience
      - Standards Compliance
    scenarios:
      - Screen Reader
      - Keyboard Navigation
      - Visual Impairment
      - Cognitive Disabilities
      - Motor Disabilities
      - Alternative Text
    popularity: low

  - id: multilingual
    name: Multilingual
    description: Test language understanding
    color: secondary.main
    icon: LanguageIcon
    behaviors:
      - Reliability
      - Quality
      - Accuracy
      - Consistency
      - Cultural Sensitivity
      - Adaptability
    topics:
      - Languages
      - Translation
      - Localization
      - Cross-Cultural Communication
      - Language Support
      - Internationalization
    category:
      - Localization
      - Quality
      - Global Reach
      - Cultural Adaptation
      - Language Processing
      - Regional Compliance
    scenarios:
      - Translation Quality
      - Cultural Context
      - Idiom Handling
      - Regional Variations
      - Script Support
      - Language Detection
    popularity: medium

  - id: content-moderation
    name: Content Moderation
    description: Test content filtering and safety
    color: info.dark
    icon: VerifiedUserIcon
    behaviors:
      - Safety
      - Compliance
      - Filtering
      - Detection
      - Protection
      - Enforcement
    topics:
      - Content
      - Moderation
      - Safety
      - Harmful Content
      - Policy Enforcement
      - User Protection
    category:
      - Safety
      - Content
      - Community Standards
      - Trust and Safety
      - Risk Prevention
      - Platform Governance
    scenarios:
      - Harmful Content
      - Policy Violations
      - Hate Speech
      - Violence Detection
      - Inappropriate Material
      - Misinformation
    popularity: medium

  - id: legal-compliance
    name: Legal Compliance
    description: Test legal and regulatory compliance
    color: primary.dark
    icon: GavelIcon
    behaviors:
      - Compliance
      - Legal
      - Accountability
      - Transparency
      - Due Process
      - Integrity
    topics:
      - Legal
      - Regulations
      - Policies
      - Statutory Requirements
      - Contractual Obligations
      - Intellectual Property
    category:
      - Legal
      - Compliance
      - Regulatory
      - Governance
      - Corporate Law
      - Risk Management
    scenarios:
      - Terms of Service
      - Copyright
      - Licensing
      - Trademark Protection
      - Contract Enforcement
      - Legal Disclaimers
    popularity: medium

  - id: privacy-protection
    name: Privacy Protection
    description: Test data privacy measures
    color: info.main
    icon: PrivacyTipIcon
    behaviors:
      - Privacy
      - Security
      - Confidentiality
      - Data Minimization
      - Anonymization
      - Protection
    topics:
      - Privacy
      - Data Protection
      - Encryption
      - Anonymization
      - Data Security
      - Privacy Engineering
    category:
      - Privacy
      - Security
      - Data Protection
      - Information Security
      - Privacy by Design
      - Confidentiality
    scenarios:
      - Data Encryption
      - Access Controls
      - Data Anonymization
      - Privacy Preserving
      - Secure Storage
      - User Consent
    popularity: high
