templates:
  - id: bias-detection
    name: Bias Detection
    description: Identify and test for AI biases
    color: primary.main
    icon: BalanceIcon
    prompt: Generate test behaviors for AI bias detection focusing on fairness, reliability, objectivity, inclusivity, equity, and consistency in AI systems
    topics:
      - Bias
      - Fairness
      - Demographics
      - Representation
      - Discrimination
      - Algorithmic Justice
    category:
      - Ethics
      - Quality
      - AI Safety
      - Social Impact
      - Diversity
      - Responsible AI
    popularity: high

  - id: multilingual
    name: Multilingual
    description: Test language understanding
    color: primary.main
    icon: LanguageIcon
    prompt: Generate test behaviors for multilingual AI systems focusing on reliability, quality, accuracy, consistency, cultural sensitivity, and adaptability across different languages and cultures
    topics:
      - Languages
      - Translation
      - Localization
      - Cross-Cultural Communication
      - Language Support
      - Internationalization
    category:
      - Localization
      - Quality
      - Global Reach
      - Cultural Adaptation
      - Language Processing
      - Regional Compliance
    popularity: medium

  - id: content-moderation
    name: Content Moderation
    description: Test content filtering and safety
    color: primary.main
    icon: VerifiedUserIcon
    prompt: Generate test behaviors for content moderation systems focusing on safety, compliance, filtering, detection, protection, and enforcement of community standards
    topics:
      - Content
      - Moderation
      - Safety
      - Harmful Content
      - Policy Enforcement
      - User Protection
    category:
      - Safety
      - Content
      - Community Standards
      - Trust and Safety
      - Risk Prevention
      - Platform Governance
    popularity: medium

  - id: privacy-protection
    name: Privacy Protection
    description: Test data privacy measures
    color: primary.main
    icon: PrivacyTipIcon
    prompt: Generate test behaviors for privacy protection systems focusing on privacy, security, confidentiality, data minimization, anonymization, and protection of user data
    topics:
      - Privacy
      - Data Protection
      - PII Detection
      - Anonymization
      - Data Security
      - Privacy Engineering
    category:
      - Privacy
      - Security
      - Data Protection
      - Information Security
      - Privacy by Design
      - Confidentiality
    popularity: high

  - id: tone-appropriateness
    name: Tone Appropriateness
    description: Test conversational tone and style
    color: primary.main
    icon: RecordVoiceOverIcon
    prompt: Generate test behaviors for tone appropriateness focusing on professionalism, empathy, respect, clarity, adaptability, and emotional intelligence in communication
    topics:
      - Tone
      - Communication Style
      - Formality
      - Emotional Context
      - Audience Awareness
      - Conversational Flow
    category:
      - Quality
      - User Experience
      - Communication
      - Interpersonal Skills
      - Brand Voice
      - Customer Relations
    popularity: high

  - id: cultural-sensitivity
    name: Cultural Sensitivity
    description: Test cultural awareness and respect
    color: primary.main
    icon: PublicIcon
    prompt: Generate test behaviors for cultural sensitivity focusing on respect, inclusivity, awareness, sensitivity, adaptability, and open-mindedness across different cultures
    topics:
      - Culture
      - Traditions
      - Customs
      - Religious Sensitivity
      - Cross-Cultural Communication
      - Global Perspectives
    category:
      - Ethics
      - Diversity
      - Social Impact
      - Global Readiness
      - Inclusivity
      - Cultural Intelligence
    popularity: medium

  - id: readability
    name: Readability
    description: Test content clarity and comprehension
    color: primary.main
    icon: MenuBookIcon
    prompt: Generate test behaviors for readability focusing on clarity, simplicity, coherence, accessibility, effectiveness, and user-friendly content design
    topics:
      - Readability
      - Comprehension
      - Plain Language
      - Structure
      - Vocabulary
      - Communication Clarity
    category:
      - Quality
      - User Experience
      - Content
      - Communication
      - Education
      - Information Design
    popularity: medium

  - id: empathy-emotional-intelligence
    name: Empathy & Emotional Intelligence
    description: Test emotional understanding and response
    color: primary.main
    icon: FavoriteIcon
    prompt: Generate test behaviors for empathy and emotional intelligence focusing on empathy, compassion, understanding, support, emotional awareness, and active listening skills
    topics:
      - Emotions
      - Mental Health
      - Support
      - Crisis Response
      - Validation
      - Emotional Support
    category:
      - User Experience
      - Social Impact
      - Mental Health
      - Customer Care
      - Human-Centered Design
      - Wellbeing
    popularity: high

  - id: creativity-innovation
    name: Creativity & Innovation
    description: Test creative problem-solving and originality
    color: primary.main
    icon: LightbulbIcon
    prompt: Generate test behaviors for creativity and innovation focusing on creativity, innovation, originality, flexibility, imagination, and problem-solving capabilities
    topics:
      - Creativity
      - Brainstorming
      - Innovation
      - Original Ideas
      - Creative Writing
      - Design Thinking
    category:
      - Quality
      - Innovation
      - Content Creation
      - Problem-Solving
      - Ideation
      - Strategic Thinking
    popularity: high

  - id: contextual-understanding
    name: Contextual Understanding
    description: Test context awareness and relevance
    color: primary.main
    icon: TroubleshootIcon
    prompt: Generate test behaviors for contextual understanding focusing on context awareness, relevance, comprehension, adaptability, discernment, and situational intelligence
    topics:
      - Context
      - Relevance
      - Situational Awareness
      - Implicit Meaning
      - Nuance
      - Background Knowledge
    category:
      - Quality
      - Intelligence
      - User Experience
      - Communication
      - Interpretation
      - Comprehension
    popularity: medium

  - id: ethical-reasoning
    name: Ethical Reasoning
    description: Test ethical decision-making and values
    color: primary.main
    icon: AccountBalanceIcon
    prompt: Generate test behaviors for ethical reasoning focusing on ethics, integrity, responsibility, moral reasoning, transparency, and accountability in decision-making
    topics:
      - Ethics
      - Morality
      - Values
      - Dilemmas
      - Responsibility
      - Social Good
    category:
      - Ethics
      - AI Safety
      - Social Impact
      - Responsible AI
      - Governance
      - Philosophy
    popularity: medium

  - id: persuasion-influence
    name: Persuasion & Influence
    description: Test persuasive communication effectiveness
    color: primary.main
    icon: CampaignIcon
    prompt: Generate test behaviors for persuasion and influence focusing on persuasiveness, influence, credibility, rhetoric, argumentation, and conviction in communication
    topics:
      - Persuasion
      - Argumentation
      - Rhetoric
      - Influence
      - Negotiation
      - Advocacy
    category:
      - Communication
      - Marketing
      - Sales
      - Leadership
      - Negotiation
      - Advocacy
    popularity: medium
