name: Preview CI/CD

# Preview deployment for both backend and frontend
# This ensures frontend gets the correct backend preview URL
# Updated: Manual trigger workflow for coordinated preview deployments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd
      reason:
        description: 'Reason for preview deployment'
        required: false
        type: string
        default: 'Preview deployment'

jobs:
  deploy-backend-preview:
    name: Deploy Backend Preview
    uses: ./.github/workflows/backend.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: ${{ github.event.inputs.environment }}
      preview: true
      deploy_only: false
      reason: ${{ github.event.inputs.reason || 'Preview deployment - Backend' }}
    secrets: inherit

  deploy-frontend-preview:
    name: Deploy Frontend Preview
    needs: deploy-backend-preview
    uses: ./.github/workflows/frontend.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: ${{ github.event.inputs.environment }}
      preview: true
      deploy_only: false
      reason: ${{ github.event.inputs.reason || 'Preview deployment - Frontend' }}
      backend_preview_url: ${{ needs.deploy-backend-preview.outputs.backend_preview_url }}
    secrets: inherit

  generate-summary:
    name: Generate Preview Deployment Summary
    needs: [deploy-backend-preview, deploy-frontend-preview]
    runs-on: ubuntu-latest
    steps:
      - name: Generate Preview Summary
        run: |
          echo "# ⚠️ PREVIEW - Service Deployment" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Deployment Details" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment:** ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Reason:** ${{ github.event.inputs.reason }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Type:** PREVIEW (NOT Live Environment)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Preview URLs" >> $GITHUB_STEP_SUMMARY
          # Debug URL information for troubleshooting
          BACKEND_URL="${{ needs.deploy-backend-preview.outputs.backend_preview_url }}"
          FRONTEND_URL="${{ needs.deploy-frontend-preview.outputs.frontend_preview_url }}"
          
          echo "Preview URL Debug:"
          echo "  - Backend URL: ${BACKEND_URL:0:30}...${BACKEND_URL: -20}"
          echo "  - Frontend URL: ${FRONTEND_URL:0:30}...${FRONTEND_URL: -20}"
          
          # Use echo to avoid printf option parsing issues with URLs starting with dashes
          echo "- **Backend Preview:** [$BACKEND_URL]($BACKEND_URL)" >> $GITHUB_STEP_SUMMARY
          echo "- **Frontend Preview:** [$FRONTEND_URL]($FRONTEND_URL)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Important Preview Warnings" >> $GITHUB_STEP_SUMMARY
          echo "- **These are NOT live ${{ github.event.inputs.environment }} services**" >> $GITHUB_STEP_SUMMARY
          echo "- **Both services receive 0% live traffic**" >> $GITHUB_STEP_SUMMARY
          echo "- **Completely isolated from live environment**" >> $GITHUB_STEP_SUMMARY
          echo "- **Frontend is configured to communicate with backend preview**" >> $GITHUB_STEP_SUMMARY
          echo "- **For testing and review purposes ONLY**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Testing Instructions" >> $GITHUB_STEP_SUMMARY
          echo "1. **Access the frontend preview URL above** to test the deployment" >> $GITHUB_STEP_SUMMARY
          echo "2. **Verify all functionality** works as expected in the preview environment" >> $GITHUB_STEP_SUMMARY
          echo "3. **Remember:** This is an isolated preview - no impact on live users" >> $GITHUB_STEP_SUMMARY
          
          echo "Preview deployment completed successfully!"
          echo "Backend:  ${{ needs.deploy-backend-preview.outputs.backend_preview_url }}"
          echo "Frontend: ${{ needs.deploy-frontend-preview.outputs.frontend_preview_url }}"