name: Publish SDK to PyPI

on:
  push:
    tags:
      - 'sdk-v*'  # Trigger on any tag that starts with 'sdk-v'
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install uv and build tools
      run: |
        echo "Hello, world!"
    