name: "[Release] 3. Publish and deploy (prd)"
on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Git
        run: |
          git config user.name "arek"
          git config user.email "a.kwasigrochsdfdsfsdf@gmail.com"
      - name: Create random file
        run: |
          echo $((RANDOM % 10000 + 1)) > random.txt
      - name: Commit changes
        run: |
          git add .
          git commit -m "Add random file"
      - name: Push changes
        run: |
          git push

