name: "[Test] SDK"

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'sdk/**'

jobs:
  test-sdk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for git diff

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: latest
        enable-cache: true
      
    - name: Test SDK
      run: |
        uv run --project sdk pytest tests/sdk/models
        uv run --project sdk pytest tests/sdk/metrics
        uv run --project sdk pytest tests/sdk/test_client.py
      continue-on-error: false
