name: Set up release
on:
  workflow_dispatch:
    inputs:
      platform_bump:
        description: 'Platform version bump'
        required: false
        type: choice
        options:
          - patch
          - minor
          - major
      backend_bump:
        description: 'Backend version bump'
        required: false
        type: choice
        options:
          - patch
          - minor
          - major
      frontend_bump:
        description: 'Frontend version bump'
        required: false
        type: choice
        options:
          - patch
          - minor
          - major

      sdk_bump:
        description: 'SDK version bump'
        required: false
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  update-release-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update release config
        run: |
          # Create JSON using jq 
          jq -n \
            --arg platform "${{ github.event.inputs.platform_bump }}" \
            --arg backend "${{ github.event.inputs.backend_bump }}" \
            --arg frontend "${{ github.event.inputs.frontend_bump }}" \
            --arg sdk "${{ github.event.inputs.sdk_bump }}" \
            '{
              platform: $platform,
              backend: $backend,
              frontend: $frontend,
              sdk: $sdk
            } | with_entries(select(.value != ""))' > release_config.json
          
          echo "Generated release_config.json:"
          cat release_config.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update release bumps: platform=${{ github.event.inputs.platform_bump }}, backend=${{ github.event.inputs.backend_bump }}, frontend=${{ github.event.inputs.frontend_bump }}"
          title: "Release Bump: platform - ${{ github.event.inputs.platform_bump }}, backend - ${{ github.event.inputs.backend_bump }}, frontend - ${{ github.event.inputs.frontend_bump }}"
          body: |
            ## Release Version Bumps
            
            - **Platform**: ${{ github.event.inputs.platform_bump }}
            - **Backend**: ${{ github.event.inputs.backend_bump }}
            - **Frontend**: ${{ github.event.inputs.frontend_bump }}
            
            This PR updates the release configuration with the selected version bumps.
          branch: release-bump-${{ github.run_number }}
          delete-branch: true