name: 'Generate Deployment Summary'
description: 'Generates deployment summary for both regular and preview deployments'
inputs:
  service-type:
    description: 'Service type (Backend, Frontend)'
    required: true
  is-preview:
    description: 'Whether this is a preview deployment'
    required: true
    default: 'false'
  environment:
    description: 'Environment (dev, stg, prd)'
    required: true
  env-display:
    description: 'Human-readable environment name'
    required: true
  service-url:
    description: 'Service URL to display'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Generate deployment summary
      shell: bash
      run: |
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ inputs.is-preview }}" = "true" ]; then
          # Preview deployment summary
          echo "## ⚠️ PREVIEW - ${{ inputs.service-type }} Service Deployed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Access Information" >> $GITHUB_STEP_SUMMARY
          echo "**Preview URL:** [${{ inputs.service-url }}](${{ inputs.service-url }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Deployment Information" >> $GITHUB_STEP_SUMMARY
          
          # Create service identifier without using the actual project name
          SERVICE_TYPE_LOWER=$(echo "${{ inputs.service-type }}" | tr '[:upper:]' '[:lower:]')
          if [ "${{ inputs.environment }}" = "prd" ]; then
            SERVICE_IDENTIFIER="production-${SERVICE_TYPE_LOWER}"
          else
            SERVICE_IDENTIFIER="${{ inputs.environment }}-${SERVICE_TYPE_LOWER}"
          fi
          
          echo "- **Service:** $SERVICE_IDENTIFIER" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment:** ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Platform:** Google Cloud Run" >> $GITHUB_STEP_SUMMARY
          echo "- **Region:** us-central1" >> $GITHUB_STEP_SUMMARY
          
          # Add commit information if available
          if [ -n "$GITHUB_SHA" ]; then
            COMMIT_SHORT=${GITHUB_SHA:0:8}
            echo "- **Commit:** [\`$COMMIT_SHORT\`](https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA)" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "- **Deployed:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          
          # Add service location information
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Service Location" >> $GITHUB_STEP_SUMMARY
          echo "- **Cloud Provider:** Google Cloud Platform" >> $GITHUB_STEP_SUMMARY
          echo "- **Service Type:** Cloud Run Container" >> $GITHUB_STEP_SUMMARY
          echo "- **Naming Pattern:** \`project-${SERVICE_TYPE_LOWER}-${{ inputs.environment }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Full Service Path:** \`projects/[project-id]/locations/us-central1/services/project-${SERVICE_TYPE_LOWER}-${{ inputs.environment }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Preview Warning" >> $GITHUB_STEP_SUMMARY
          echo "- **This is a PREVIEW deployment, NOT live ${{ inputs.environment }}**" >> $GITHUB_STEP_SUMMARY
          echo "- **Receives 0% live traffic**" >> $GITHUB_STEP_SUMMARY
          echo "- **Isolated from live environment**" >> $GITHUB_STEP_SUMMARY
          echo "- **Only accessible via the tagged URL above**" >> $GITHUB_STEP_SUMMARY
          echo "- **For testing and review purposes only**" >> $GITHUB_STEP_SUMMARY
        else
          # Regular deployment summary - no URL shown since it's a secret
          echo "## ✅ ${{ inputs.env-display }} - ${{ inputs.service-type }} Service Deployed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Deployment Status" >> $GITHUB_STEP_SUMMARY
          echo "- **This is the LIVE ${{ inputs.env-display }} service**" >> $GITHUB_STEP_SUMMARY
          echo "- **New revision is receiving 100% traffic**" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ inputs.environment }}" = "prd" ]; then
            echo "- **Serving real user traffic**" >> $GITHUB_STEP_SUMMARY
            echo "- **Handle with care - affects users**" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Serving ${{ inputs.env-display }} environment traffic**" >> $GITHUB_STEP_SUMMARY
            echo "- **Handle with care - affects ${{ inputs.env-display }} users**" >> $GITHUB_STEP_SUMMARY
          fi
        fi
        
        echo "✅ Deployment summary generated for ${{ inputs.service-type }} (${{ inputs.is-preview == 'true' && 'PREVIEW' || inputs.env-display }})"

